### ISSUE TITLE
Upgrading to latest version listen is not a function

### ISSUE THREAD

**Issue by howdu** [WickyNilliams/enquire.js#67]
Hi, after upgrading from: 1.5.6 to 2.0.2 I am getting error: enquire.register(...).register(...).register(...).listen is not a function
Source File: http://projects.web2works.co.uk/microdat2/webapp/templates/default/js/plugin/bootstrap.plugins.js
Line: 1180

Example URL: http://projects.web2works.co.uk/microdat2/

Its strange because the listen() function calls fine inside: http://projects.web2works.co.uk/microdat2/webapp/templates/default/js/initialize.js although further down the page inside: 

``` javascript
var $targets = $("img[data-hi-res]");
if($targets.length){
    enquire.register("screen and (min-width:481px)", {          
        match: function() {
            $targets.each(function() {
                var $this = $(this);
                $this.data("lowRes", $this.attr("src"));            
                $this.attr("src", $this.data("hiRes"));
            });
        },          
        unmatch: function() {
            $targets.each(function() {
                var $this = $(this);
                $this.attr("src", $this.data("lowRes"));
            });
        }           
    }).listen();
}
```

Although the code inside: http://projects.web2works.co.uk/microdat2/webapp/templates/default/js/plugin/bootstrap.plugins.js has the error

``` javascript
// Call methods based on media query
enquire
    .register(this.config.media_query.mobile, {
        setup : function() {
            self.buildMobileMenu();
        },
        match : function() {
            self.destroy();
            self.mobileMenu();
            self.mobileFooterMenu();
        }
    })
    .register(this.config.media_query.tablet, {
        match : function() {
            self.destroy();
            self.tabletMenu();
        }
    })
    .register(this.config.media_query.desktop, {
        match : function() {
            self.destroy();
            self.desktopMenu();
        }
    })
.listen();
```
